Language.data.cn = {

	DOSIERUNG : "<b>剂量</b>",
	DOSIERUNG_INFO : "给药剂量",
	F: "F <i>in %</i>",
	F_INFO: "生物利用度",
	DOSIS: "D <i>in mg</i>",
	DOSIS_INFO: "剂量",
	INTERVALL: "<span style=\"font-size:1.5em\">&#964;</span> <i>in h</i>",
	INTERVALL_INFO: "给药间隔",
	PREDOSE: "C<sub>min</sub> <i>in mg/L</i>",
	PREDOSE_INFO: "在第一次剂量的稳态浓度",
	SPRACHE: "语",
	SPRACHE_INFO: "选择一种语言",
	
	POPULATIONSDATEN : "<b>人口数据</b>",
	POPULATIONSDATEN_INFO : "PK参数技术信息",
	ABSORPTION: "t<sub>in</sub> <i>in h</i>",
	ABSORPTION_INFO: "口服后吸收半衰期",
	HALBWERTSZEIT: "t<sub>1\2</sub> <i>in h</i>",
	HALBWERTSZEIT_INFO: "的浓度半衰期",
	VOLUMEN: "V <i>in L</i>",
	VOLUMEN_INFO: "分布容积",
	CLEARANCE: "Cl <i>in L/h</i>",
	CLEARANCE_INFO: "计算间隙",
	ELIKONSTANTE: "k<sub>e</sub> <i>in <sup>-h</sup></i>",
	ELIKONSTANTE_INFO: "计算消除常数",
	
	PERSONALISIERUNG:"<b>个性化  Css</b>",
	PERSONALISIERUNG_INFO:"个人PK参数的计算",
	KONZENTRATION1: "C<sub>1</sub>",
	KONZENTRATION1_INFO: "浓度下一个剂量（槽前）",
	ZEIT1: "t<sub>1</sub>",
	ZEIT1_INFO: "相对于治疗开始测量时间",
	KONZENTRATION2: "C<sub>2</sub>",
	KONZENTRATION2_INFO: "浓度测量槽前（消除相）",
	ZEIT2: "t<sub>2</sub>",
	ZEIT2_INFO: "相对于治疗开始测量时间",
	RECHENART: "Keine Berechnung",
	RECHENART_INFO: "Angaben für die Berechnung fehlen",
	RECHENART_VARIATION : "Variation V <b>und</b> t<sub>1/2</sub>",
	RECHENART_VARIATION_INFO : "Variation von entweder Verteilungsvolumen oder Halbwertszeit bei der Berechnung",
	RECHENART_PRECISE : "Personalisiertes V <b>und</b> t<sub>1/2</sub>",
	RECHENART_PRECISE_INFO : "Exakte Berechnung von Verteilungsvolumen und Halbwertszeit",
	
	BEREICH:"<b>Therapeutischer Bereich</b>",
	BEREICH_INFO:"Bereich der Konzentraton aus der Analysenliste",
	OBERE_GRENZE: "Obere Grenze",
	OBERE_GRENZE_INFO: "Obere Grenze entweder Talspiegel oder Spitzenspiegel",
	UNTERE_GRENZE: "Untere Grenze",
	UNTERE_GRENZE_INFO: "Untere Grenze des Talspiegels",
		
	ORDINATE : "C mg/L",
	ABSZISSE : "t in h"
	
};