Language.data.en = {

	DOSIERUNG : "<b>Dosage</b>",
	DOSIERUNG_INFO : "Applied dosage",
	F: "F <i>in %</i>",
	F_INFO: "Bioavailability",
	DOSIS: "D <i>in mg</i>",
	DOSIS_INFO: "Dose",
	INTERVALL: "<span style=\"font-size:1.5em\">&#964;</span> <i>in h</i>",
	INTERVALL_INFO: "Dosing interval",
	PREDOSE: "C<sub>min</sub> <i>in mg/L</i>",
	PREDOSE_INFO: "Steady-State-Conzentration at first dose",
	SPRACHE: "Language",
	SPRACHE_INFO: "Select language",
	
	POPULATIONSDATEN : "<b>Population data</b>",
	POPULATIONSDATEN_INFO : "PK parameters in summary of product characteristics",
	ABSORPTION: "t<sub>in</sub> <i>in h</i>",
	ABSORPTION_INFO: "Half-life of absorption after oral administration",
	HALBWERTSZEIT: "t<sub>1\2</sub> <i>in h</i>",
	HALBWERTSZEIT_INFO: "Time to reach half of plasma concentration",
	VOLUMEN: "V <i>in L</i>",
	VOLUMEN_INFO: "Volume",
	CLEARANCE: "Cl <i>in L/h</i>",
	CLEARANCE_INFO: "Calculated clearance",
	ELIKONSTANTE: "k<sub>e</sub> <i>in <sup>-h</sup></i>",
	ELIKONSTANTE_INFO: "Calculated elimination constant",
	
	PERSONALISIERUNG:"<b>Personalization Css</b>",
	PERSONALISIERUNG_INFO:"Calculation of individual PK parameters",
	KONZENTRATION1: "C<sub>1</sub>",
	KONZENTRATION1_INFO: "Concentration measured before the next dose (trough)",
	ZEIT1: "t<sub>1</sub>",
	ZEIT1_INFO: "Time of measurement relative to the start of therapy",
	KONZENTRATION2: "C<sub>2</sub>",
	KONZENTRATION2_INFO: "Concentration measured before trough (in elimination phase)",
	ZEIT2: "t<sub>2</sub>",
	ZEIT2_INFO: "Time of measurement relative to the start of therapy",
	RECHENART: "No calculation",
	RECHENART_INFO: "Required variables are missing",
	RECHENART_VARIATION : "Variation V <b>and</b> t<sub>1/2</sub>",
	RECHENART_VARIATION_INFO : "Variation of either volume of distribution or half-life in the calculation",
	RECHENART_PRECISE : "Personalized V <b>and</b> t<sub>1/2</sub>",
	RECHENART_PRECISE_INFO : "Exact calculation of volume of distribution and half-life",
	
	BEREICH:"<b>Therapeutic range</b>",
	BEREICH_INFO:"Bange of concentration according to lab",
	OBERE_GRENZE: "Upper Limi",
	OBERE_GRENZE_INFO: "Upper Limit of trough or peak concentration",
	UNTERE_GRENZE: "Lower Limit",
	UNTERE_GRENZE_INFO: "Lower Limit of trough concentration",
		
	ORDINATE : "C mg/L",
	ABSZISSE : "t in h"
	
};